id = "anya"
name = "Anya Theme"
version = "0.0.2"
schema_version = 1
description = "Keeping it minimal and readable"
repository = "https://github.com/anya-theme/anya-zed"
authors = ["choednwn <contact@choednwn.com>"]
themes = ["themes/anya.json"]
languages = []

[lib]

[grammars]

[language_servers]
